name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to publish
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
      - run: npm ci

      - run: npm run lint
      - run: npm run build

      - run: npm version ${{ inputs.version }}
      - run: git push origin main --follow-tags
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
